//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_ogrenci_kayit.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIDARI
    {
        public short idid { get; set; }
        public string idAd { get; set; }
        public string idSoyad { get; set; }
        public string idBirimi { get; set; }
    }
}
