//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_ogrenci_kayit.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRENCILER
    {
        public short Ogrid { get; set; }
        public string OgrAd { get; set; }
        public string OgrSoyad { get; set; }
        public Nullable<short> OgrNo { get; set; }
        public string OgrBolum { get; set; }
    }
}
